package stud.kea.dk.scrapbasketsultimateproject.repository;

import org.springframework.stereotype.Repository;
import stud.kea.dk.scrapbasketsultimateproject.model.AnimeData;

import java.util.ArrayList;
import java.util.List;

@Repository
public class AnimeRepository {
    public List<AnimeData> getAllAnimeData() {
        List<AnimeData> animeData = new ArrayList<>();
        animeData.add(new AnimeData(1, "Angel Beats!", "https://aniwave.to/watch/angel-beats.lzz/ep-1", "Action, Comedy, Drama, School, Supernatural", " ", " ", " ", "x", " ", "Yes", "2", "20-10-18", "02-08-23", "Dub", " ", " "));
        animeData.add(new AnimeData(2, "Re:Zero Starting Life in Another World", "https://aniwave.to/filter?keyword=Re%3AZero+Starting+Life+in+Another+World", "Drama, Fantasy, Psychological, Thriller", "", "", "", "", "x+++", "yes", "10+", "20-10-18", "22-04-23", "Dub", "", ""));
        animeData.add(new AnimeData(3, "No Game, No Life", "https://aniwave.to/filter?keyword=No+Game%2C+No+Life", "Adventure, Comedy, Fantasy, Game, Supernatural", "", "", "", "", "x+", "yes", "8", "09-10-18", "02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(4, "Sword Art Online", "https://aniwave.to/filter?keyword=Sword+Art+Online", "Action, Adventure, Fantasy, Game, Romance", "", "", "", "", "x++", "yes", "10+", "09-10-18", "02-08-23", "Dub", "Yes", "https://manganato.com/search/story/sword_art_online"));
        animeData.add(new AnimeData(5, "AntiMagic Academy 35th Test Platoon", "https://aniwave.to/watch/anti-magic-academy-the-35th-test-platoon.n3k/ep-1", "Action, Fantasy, Harem, Military, Romance, Supernatural", "", "", "x", "", "","no", "", "02-10-18", "02-08-23", "Sub", "", ""));
        animeData.add(new AnimeData(6, "Campione!", "https://aniwave.to/watch/campione.rkp/ep-1", "Comedy, Fantasy, Harem, Magic, Romance", "", "", "x", "", "","no","", "02-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(7, "Highschool DxD", "https://aniwave.to/filter?keyword=Highschool+DxD", "Comedy, Demons, Ecchi, Harem, Romance, School", "", "", "", "", "x+", "yes","2","27-09-18", "02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(8, "Freezing", "https://aniwave.to/filter?keyword=Freezing", "Action, Drama, Ecchi, Harem, Martial Arts, Romance, Sci-Fi, Seinen", "", "", "", "x", "", "yes","2", "01-10-18", "02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-sk953193"));
        animeData.add(new AnimeData(9, "Hajimate no Gal", "https://aniwave.to/watch/my-first-girlfriend-is-a-gal.wyrl/ep-1", "Comedy, Romance, School, Shounen", "", "x", "", "", "", "no", "","07-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(10, "Heaven's Lost Property", "https://aniwave.to/filter?keyword=Heaven%27s+Lost+Property", "Comedy, Ecchi, Harem, Sci-Fi, Shounen, Supernatural", "", "", "", "x", "","yes","2", "24-09-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-yc956437"));
        animeData.add(new AnimeData(11, "Highschool of the Dead", "https://aniwave.to/watch/high-school-of-the-dead.1n5q/ep-1", "Action, Horror, Supernatural", "", "", "", "", "x+", "no", "", "02-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-nu964455"));
        animeData.add(new AnimeData(12, "Rosario to Vampire", "https://aniwave.to/watch/rosario-vampire.jvpn/ep-1", "Comedy, Fantasy, Harem, Romance, School, Shounen, Vampire", "", "", "x", "", "", "no", "", "02-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(13, "Sekirei", "https://aniwave.to/watch/sekirei.lll3/ep-1", "Action, Comedy, Ecchi, Harem, Super Power", "", "", "x", "", "", "no", "","29-09-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(14, "So, I Can't Play H!", "https://aniwave.to/watch/so-i-cant-play-h.z1mw/ep-1", "Comedy,Romance, Supernatural", "x", "", "", "", "", "No", "","01-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(15, "The Devil is a Part-Timer!", "https://aniwave.to/filter?keyword=The+Devil+is+a+Part-Timer%21", "Comedy, Demons, Fantasy, Romance, Shounen, Shounen Ai", "", "", "", "", "x+", "yes","5","03-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-io951697"));
        animeData.add(new AnimeData(16, "The Testament of Sister New Devil", "https://aniwave.to/watch/the-testament-of-sister-new-devil.42rm/ep-1", "Action, Ecchi, Fantasy, Harem, Romance", "", "", "x", "", "", "no", "","29-09-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(17, "Ah! my Goddess", "https://aniwave.to/filter?keyword=Ah%21+my+Goddess", "Comedy, Magic, Romance, Seinen, Supernatural", "", "", "x", "", "", "no", "","08-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-mz955208"));
        animeData.add(new AnimeData(18, "Goblin Slayer", "https://aniwave.to/filter?keyword=Goblin+Slayer", "Action, Adventure, Fantasy, Magic", "", "", "", "", "x", "yes","5","08-10-18","02-08-23", "Sub", "yes", "https://chapmanganato.to/manga-us971827"));
        animeData.add(new AnimeData(19, "Accel World", "https://aniwave.to/filter?keyword=Accel+World", "Action, Romance, School, Sci-Fi, Isekai", "", "", "", "x", "","maybe", "", "15-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-ob952758"));
        animeData.add(new AnimeData(20, "Future Diary", "https://aniwave.to/watch/future-diary.ozj/ep-1", "Action, Horror, Mystery, Psychological, Shounen, Supernatural, Thriller, Suspense", "", "", "", "x", "", "maybe", "","18-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(21, "Btooom!", "https://aniwave.to/watch/btooom.z883/ep-1", "Action, Psychological, Sci-Fi, Seinen", "", "", "x", "", "","no", "", "17-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-jd954886"));
        animeData.add(new AnimeData(22, "Log Horizon", "https://aniwave.to/filter?keyword=Log+Horizon", "Action, Adventure, Fantasy, Isekai, Magic", "", "", "x", "", "","yes","4", "12-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(23, "Hack // Sign", "https://aniwave.to/watch/hacksign.wqqk/ep-1", "Adventure, Fantasy, Mystery, Sci-Fi, Super Power, Isekai, Magic", "", "x", "", "", "", "no","", "N/A","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(24, "Love Hina", "https://aniwave.to/filter?keyword=Love+Hina", "Comedy, Ecchi, Harem, Romance, Shounen, Slice of Life", "", "", "x", "", "","maybe","", "08-09-18","02-08-23", "Dub", "yes", "https://manganato.com/manga-cs956801"));
        animeData.add(new AnimeData(25, "Mahou Sensei Negima!", "https://aniwave.to/filter?keyword=Mahou+Sensei+Negima%21", "Comedy, Ecchi, Fantasy, Harem, Romance, School, Shounen, Super Power, Supernatural, Vampire, Magic", "", "", "", "x","", "maybe","", "08-09-18","02-08-23", "Dub", "yes", "https://chapmanganato.to//manga-av956604"));
        animeData.add(new AnimeData(26, "UQ Holder", "https://aniwave.to/watch/uq-holder.79qj/ep-1", "Action, Fantasy, School, Sci-Fi, Shounen, Vampire, Magic", "", "", "", "x", "","maybe","", "13-09-18","02-08-23", "Sub", "yes", "https://chapmanganato.to/manga-ro952049"));
        animeData.add(new AnimeData(27, "One punch man", "https://aniwave.to/filter?keyword=One+punch+man", "Action, Comedy, Parody, Sci-Fi, Seinen, Super Power, Supernatural, Demons", "", "", "", "x", "","maybe","", "N/A","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-wd951838"));
        animeData.add(new AnimeData(28, "Chobits", "https://aniwave.to/watch/chobits.29ql/ep-1", "Comedy, Drama, Ecchi, Romance, Sci-Fi, Seinen", "", "", "x", "", "","no", "", "07-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-tp955950"));
        animeData.add(new AnimeData(29, "Zombieland-Saga", "https://aniwave.to/filter?keyword=Zombieland-Saga", "Comedy, Music, Parody, Supernatural", "", "", "x", "", "","no","", "21-10-18","02-08-23", "Sub", "", ""));
        animeData.add(new AnimeData(30, "One Piece (Ongoing)", "https://aniwave.to/filter?keyword=One+Piece", "Action, Adventure, Comedy, Drama, Fantasy, Shounen, Super Power", "", "", "", "x", "", "maybe","", "N/A","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-aa951409"));
        animeData.add(new AnimeData(31, "Naruto", "https://aniwave.to/filter?keyword=Naruto", "Action, Adventure, Comedy, Drama, Fantasy, Martial Arts, School, Shounen, Super Power, Supernatural, Demons", "", "", "", "x", "","yes", "2","N/A","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-ng952689"));
        animeData.add(new AnimeData(32, "Boruto Next generation (Ongoing)", "https://aniwave.to/filter?keyword=Boruto+Next+generation", "Action, Adventure, Fantasy, Martial Arts, School, Shounen, Super Power", "", "", "x", "", "","no", "2","N/A","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-tl971246"));
        animeData.add(new AnimeData(33, "ReLIFE", "https://aniwave.to/watch/relife.yk0/ep-1", "Comedy, Drama, Romance, School, Seinen, Slice of Life", "", "", "", "", "x","yes", "2","20-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-me951739"));
        animeData.add(new AnimeData(34, "Grimgar: Ashes and Illusion", "https://aniwave.to/watch/grimgar-of-fantasy-and-ash.41k/ep-1", "Action, Adventure, Drama, Fantasy, Isekai, Magic", "", "", "", "", "x","yes", "6","21-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(35, "Interviews With Monster Girls", "https://aniwave.to/filter?keyword=Interviews+With+Monster+Girls", "Comedy, Fantasy, School, Seinen, Slice of Life, Supernatural, Vampire", "", "", "", "", "x+","yes","10+","22-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(36, "Overlord", "https://aniwave.to/filter?keyword=Overlord", "Action, Adventure, Fantasy, Vampire, Isekai, Demons, Magic", "", "", "", "", "x+","yes", "10+","19-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(37, "Miss Kobayashi's Dragon Maid", "https://aniwave.to/filter?keyword=Miss+Kobayashi%27s+Dragon+Maid", "Comedy, Fantasy, Seinen, Slice of Life, Isekai, Magic", "", "", "", "", "x+","yes", "5","23-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(38, "Monster Musume: Everyday Life with Monster Girls", "https://aniwave.to/filter?keyword=Monster+Musume%3A+Everyday+Life+with+Monster+Girls", "Comedy, Ecchi, Fantasy, Harem, Romance, Seinen, Demons", "", "", "", "x", "","maybe", "", "24-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(39, "Is It Wrong to Try to Pick Up Girls in a Dungeon?", "https://aniwave.to/filter?keyword=Is+It+Wrong+to+Try+to+Pick+Up+Girls+in+a+Dungeon%3F", "Action, Adventure, Comedy, Fantasy, Romance, Isekai, Magic", "", "", "", "", "x+++","yes", "10+","24-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(40, "Sword Oratoria: Is it Wrong to Try to Pick Up Girls in a Dungeon?", "https://aniwave.to/watch/sword-oratoria-is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon-on-the-side.k8wr/ep-1", "Action, Adventure, Comedy, Fantasy, Magic", "", "", "", "x", "","maybe", "3", "27-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(41, "Haganai: I don't have many friends", "https://aniwave.to/filter?keyword=Haganai%3A+I+don%27t+have+many+friends", "Comedy, Ecchi, Harem, Romance, School, Slice of Life", "", "", "", "", "x+","yes", "2","25-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(42, "Your Lie in April", "https://aniwave.to/watch/your-lie-in-april.7w6/ep-1", "Drama, Music, Romance, School, Shounen, Slice of Life", "", "", "", "", "x+++","yes", "10+","26-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(43, "Snow White with the Red Hair", "https://aniwave.to/filter?keyword=Snow+White+with+the+Red+Hair", "Drama, Fantasy, Romance, Shoujo", "", "", "x", "", "", "maybe","", "26-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(44, "How Not to Summon a Demon Lord", "https://aniwave.to/watch/how-not-to-summon-a-demon-lord.4597/ep-1", "Comedy, Ecchi, Fantasy, Harem, Super Power, Isekai, Demons, Magic", "", "", "", "x", "","yes", "4","27-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(45, "Gate", "https://aniwave.to/filter?keyword=Gate", "Action, Adventure, Fantasy, Military, Isekai, Magic", "", "", "", "", "x++","yes", "10+","01-11-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-qp952972"));
        animeData.add(new AnimeData(46, "Erased", "https://aniwave.to/watch/erased.kkw/ep-1", "Drama, Mystery, Psychological, School, Seinen, Supernatural, Thriller, Suspense", "", "", "", "", "x+","maybe", "5","02-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(47, "Infinite Stratos", "https://aniwave.to/filter?keyword=Infinite+Stratos", "Action, Comedy, Ecchi, Harem, Mecha, Romance, Sci-Fi", "", "", "x", "", "", "maybe","", "03-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(48, "DARLING in the FRANXX", "https://aniwave.to/watch/darling-in-the-franxx.rv5n/ep-1", "Action, Drama, Mecha, Military, Psychological, Romance, Sci-Fi, Space", "", "", "", "", "x","yes", "", "05-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(49, "Mysterious Girlfriend X", "https://aniwave.to/watch/mysterious-girlfriend-x.p7x/ep-1", "Ecchi, Mystery, Romance, School, Seinen", "", "", "x", "", "", "no", "", "05-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(50, "Death Parade", "https://aniwave.to/watch/death-parade.6lj9/ep-1", "Drama, Mystery, Psychological, Supernatural, Thriller, Suspense", "", "", "", "x", "","maybe","", "06-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(51, "Restaurant to Another World", "https://aniwave.to/filter?keyword=Restaurant+to+Another+World", "Fantasy, Slice of Life, Gourmet, Isekai, Iyashikei, Demons", "", "", "", "x", "","yes", "4","07-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(52, "Death March to the Parallel World Rhapsody", "https://aniwave.to/watch/death-march-to-the-parallel-world-rhapsody.73jy/ep-1", "Action, Adventure, Comedy, Fantasy, Harem, Isekai, Demons, Magic", "", "", "x", "", "","yes", "2","06-11-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-sh953216"));
        animeData.add(new AnimeData(53, "Girls Und Panzer", "https://aniwave.to/filter?keyword=Girls+Und+Panzer", "Action, Military, Parody, School, Sports", "", "", "", "", "x", "yes", "2","07-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(54, "Violet Evergarden", "https://aniwave.to/filter?keyword=Violet+Evergarden", "Drama, Fantasy, Military, Slice of Life", "", "", "", "", "x+++","yes", "10+","08-11-18","14-12-23", "Dub", "", ""));
        animeData.add(new AnimeData(55, "The Ancient Magus' Bride", "https://aniwave.to/filter?keyword=The+Ancient+Magus%27+Bride", "Drama, Fantasy, Romance, Shounen, Slice of Life, Supernatural, Magic", "", "", "", "", "x+","yes", "3","09-11-18","06-05-23", "Dub", "", ""));
        animeData.add(new AnimeData(56, "Gosick", "https://aniwave.to/watch/gosick.5210/ep-1", "Drama, Military, Mystery, Romance, School", "", "", "", "", "x","yes","", "10-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(57, "Beyond the Boundary", "https://aniwave.to/filter?keyword=Beyond+the+Boundary", "Action, Drama, Fantasy, School, Slice of Life, Super Power, Supernatural, Demons, Magic", "", "", "", "x", "","maybe","", "11-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(58, "Welcome to the N.H.K.", "https://aniwave.to/watch/welcome-to-the-n-h-k.ynp/ep-1", "Comedy, Drama, Psychological, Romance, Slice of Life", "", "", "x", "", "", "no","", "08-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(59, "Dragonball Z", "https://aniwave.to/filter?keyword=Dragonball+Z", "Action, Adventure, Comedy, Fantasy, Martial Arts, Shounen, Space, Super Power, Supernatural", "", "", "", "x", "", "no", "", "N/A", "02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-me955161"));
        animeData.add(new AnimeData(60, "IRODUKU - The World in Colors", "https://aniwave.to/watch/iroduku-the-world-in-colors.46l7/ep-1", "Drama, Fantasy, Romance, School, Slice of Life, Supernatural, Isekai, Magic", "", "", "", "", "x+++","yes", "","11-11-18", "02-08-23", "Sub", "", ""));
        animeData.add(new AnimeData(61, "Charlotte", "https://aniwave.to/filter?keyword=charlotte", "Comedy, Drama, Romance, School, Sci-Fi, Super Power, Supernatural", "", "", "", "x", "","maybe", "", "11-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(62, "Love, Chunibyo, and other delusions!", "https://aniwave.to/filter?keyword=Love%2C+Chunibyo%2C+and+other+delusions%21", "Comedy, Drama, Parody, Romance, School, Slice of Life", "", "", "", "", "x","yes", "3","12-11-18", "21-02-24", "Dub", "", ""));
        animeData.add(new AnimeData(63, "A Silent Voice (Movie)", "https://aniwave.to/watch/a-silent-voice.4wzo/ep-1", "Drama, Romance, School, Shounen, Slice of Life", "", "", "", "", "x+","yes", "10+","13-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(64, "The Disappearance of Haruhi Suzumiya (Movie)", "https://aniwave.to/watch/the-disappearance-of-haruhi-suzumiya.0xvk/ep-1", "Drama, Mystery, School, Sci-Fi, Supernatural", "", "", "", "x", "","no", "", "13-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(65, "Hyouka", "https://aniwave.to/watch/hyouka.lqq/ep-1", "Mystery, Romance, School, Slice of Life", "", "", "", "x", "","no", "", "13-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(66, "Myriad Colors Phantom World", "https://aniwave.to/watch/myriad-colors-phantom-world.oo4/ep-1", "Action, Comedy, Ecchi, Fantasy, Harem, School, Slice of Life, Super Power, Supernatural", "", "", "x", "", "", "no", "", "14-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(67, "Tamako Market", "https://aniwave.to/filter?keyword=Tamako+Market", "Comedy, School, Slice of Life, Iyashikei", "", "", "", "x", "","yes", "2","14-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(68, "Tokyo ESP", "https://aniwave.to/watch/tokyo-esp.8n2o/ep-1", "Action, Comedy, Fantasy, Sci-Fi, Seinen, Shounen, Super Power, Supernatural", "", "", "x", "", "", "no", "", "14-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(69, "Air", "https://aniwave.to/watch/air.1o9x/ep-1", "Drama, Romance, Slice of Life, Supernatural, Magic", "", "x", "", "", "", "no", "","15-11-18", "02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(70, "K-On", "https://aniwave.to/filter?keyword=K-On", "Comedy, Music, School, Seinen, Slice of Life, Iyashikei", "", "", "", "x", "","maybe", "", "15-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(71, "Anohana: The Flower We Saw That Day", "https://aniwave.to/filter?keyword=Anohana%3A+The+flower+we+saw+that+day", "Drama, Romance, Slice of Life, Supernatural", "", "", "", "", "x+++","yes", "10+","16-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(72, "Toradora", "https://aniwave.to/filter?keyword=toradora", "Comedy, Drama, Romance, School, Slice of Life", "", "", "", "", "x","yes", "2","16-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(73, "A Certain Magical Index", "https://aniwave.to/filter?keyword=A+Certain+Magical+Index+", "Action, Fantasy, Sci-Fi, Super Power, Supernatural, Magic", "", "", "x", "", "", "no", "", "17-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(74, "A Certain Scientific Railgun", "https://aniwave.to/filter?keyword=A+Certain+Scientific+Railgun", "Action, Fantasy, School, Sci-Fi, Shounen, Super Power", "", "", "x", "", "", "no", "", "18-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(75, "5 Centimeters Per Second (Movie)", "https://aniwave.to/watch/5-centimeters-per-second.v50l/ep-1", "Drama, Romance, School, Slice of Life", "", "", "", "x", "","no", "", "18-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(76, "Upotte", "https://aniwave.to/watch/upotte.lyrq/ep-1", "Action, Comedy, Ecchi, Military, Seinen", "", "x", "", "", "", "no", "","19-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(77, "Your Name (Movie)", "https://aniwave.to/watch/your-name.nkll/ep-1", "Drama, Romance, School, Supernatural", "", "", "", "", "x+++","yes", "10+","19-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(78, "The Garden of Words (Short Film)", "https://aniwave.to/watch/the-garden-of-words.l38n/ep-1", "Drama, Psychological, Romance, School, Slice of Life", "", "", "", "", "x","yes", "3","19-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(79, "Psychic School Wars (Movie)", "https://aniwave.to/watch/psychic-school-wars.2zj5/ep-1", "Romance, School, Sci-Fi, Magic", "", "", "", "x", "","no", "", "19-11-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(80, "Made in Abyss", "https://aniwave.to/filter?keyword=Made+in+Abyss", "Adventure, Drama, Fantasy, Horror, Mystery, Sci-Fi, Seinen", "", "", "", "", "x+++", "maybe", "3","19-11-18","02-08-23", "Dub", "", ""));

        /**
         * animeData.add(new AnimeData(81, "SHIMONETA: A Boring World Where the Concept of Dirty Jokes Doesn't Exist", "https://aniwave.to/watch/shimoneta-a-boring-world-where-the-concept-of-dirty-jokes-doesnt-exist.19p/ep-1", "Comedy, Ecchi, Parody, School", "", "", "", "", "", "x", "", "maybe", "", "2", "", "19-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(82, "That Time I Got Reincarnated as a Slime", "https://aniwave.to/filter?keyword=That+Time+I+Got+Reincarnated+as+a+Slime", "Action, Adventure, Comedy, Fantasy, Super Power, Isekai, Demons, Magic", "", "", "", "", "", "x++", "yes", "10", "", "20-11-18", "", "03-06-23", "Sub", "", ""));
         * animeData.add(new AnimeData(83, "Jin-Roh: The Wolf Brigade (Movie)", "https://aniwave.to/watch/jin-roh-the-wolf-brigade.myk8/ep-1", "Action, Drama, Military, Psychological, Romance, Seinen, Thriller", "", "", "", "", "", "x", "", "no", "", "20-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(84, "Fairy Tail (Didn't finish)", "https://aniwave.to/watch/fairy-tail.n48/ep-1", "Action, Adventure, Comedy, Fantasy, Shounen, Super Power, Demons, Magic", "", "", "", "", "", "x", "", "maybe", "", "20-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(85, "The Girl Who Leapt Through Time (Movie)", "https://aniwave.to/watch/the-girl-who-leapt-through-time.7116/ep-1", "Drama, Romance, School, Sci-Fi", "", "", "", "", "", "x", "maybe", "", "", "20-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(86, "Orange", "https://aniwave.to/watch/orange.xr9w/ep-1", "Drama, Romance, School, Sci-Fi, Shoujo, Super Power, Supernatural", "", "", "", "", "", "x", "", "no", "", "20-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(87, "Kokoro Connect", "https://aniwave.to/watch/kokoro-connect.nvl/ep-1", "Drama, Romance, School, Slice of Life, Supernatural", "", "", "", "", "", "x", "yes", "2", "", "21-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(88, "In Another World With My Smartphone", "https://aniwave.to/watch/in-another-world-with-my-smartphone.48qx/ep-1", "Adventure, Comedy, Fantasy, Harem, Romance, Isekai, Magic", "", "", "", "", "", "x+", "yes", "10", "", "23-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(89, "Knight’s & Magic", "https://aniwave.to/watch/knights-magic.o69y/ep-1", "Action, Fantasy, Mecha, School, Isekai, Demons, Magic", "", "", "x", "", "", "yes", "8", "", "24-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(90, "KonoSuba: God's Blessing on This Wonderful World!", "https://aniwave.to/filter?keyword=KonoSuba%3A+God%27s+Blessing+on+This+Wonderful+World%21", "Adventure, Comedy, Ecchi, Fantasy, Parody, Isekai, Magic", "", "", "", "", "", "x++", "yes", "10", "", "24-11-18", "", "02-08-23", "Sub", "", ""));
         * animeData.add(new AnimeData(91, "As the Moon, So Beautiful", "https://aniwave.to/watch/tsukigakirei.lk0n/ep-1", "Drama, Romance, School, Slice of Life", "", "", "", "", "", "x", "", "yes", "", "24-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(92, "The Ambition of Oda Nobuna", "https://aniwave.to/watch/the-ambition-of-oda-nobuna.x3v/ep-1", "Action, Comedy, Drama, Harem, Military, Romance, Isekai", "", "", "x", "", "", "maybe", "2", "", "25-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(93, "Problem Children are Coming from Another World, Aren't They?", "https://aniwave.to/watch/problem-children-are-coming-from-another-world-arent-they.zl6m/ep-1", "Action, Comedy, Fantasy, Super Power, Supernatural, Vampire, Isekai, Demons", "", "", "", "", "", "x", "", "no", "", "25-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(94, "The Familiar of Zero", "https://aniwave.to/filter?keyword=The+Familiar+of+Zero", "Action, Adventure, Comedy, Ecchi, Fantasy, Harem, Romance, School, Isekai, Magic", "", "x", "", "", "", "no", "", "25-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(95, "Outbreak Company", "https://aniwave.to/watch/outbreak-company.pox/ep-1", "Comedy, Fantasy, Harem, Military, Parody, School, Isekai, Magic", "", "", "", "", "", "x", "", "maybe", "4", "", "26-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(96, "Rascal Does Not Dream of Bunny Girl Senpai", "https://aniwave.to/filter?keyword=Rascal+Does+Not+Dream+of+Bunny+Girl+Senpai", "Comedy, Drama, Mystery, Psychological, Romance, School, Supernatural", "", "", "", "", "", "x+++", "yes", "", "", "26-11-18", "", "02-08-23", "Sub", "", ""));
         * animeData.add(new AnimeData(97, "Noragami: Stray God", "https://aniwave.to/filter?keyword=Noragami%3A+Stray+God", "Action, Adventure, Comedy, Fantasy, Shounen, Supernatural", "", "", "", "", "", "x", "", "no", "", "26-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(98, "Gamers!", "https://aniwave.to/watch/gamers.47rx/ep-1", "Comedy, Drama, Parody, Romance, School, Slice of Life", "", "", "", "", "", "x", "", "maybe", "2", "", "27-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(99, "Recovery of an MMO Junkie", "https://aniwave.to/watch/recovery-of-an-mmo-junkie.3lz6/ep-1", "Comedy, Fantasy, Josei, Parody, Romance, Slice of Life", "", "", "x", "", "", "no", "2", "", "27-11-18", "", "02-08-23", "Dub", "", ""));
         * animeData.add(new AnimeData(100, "And You Thought There Is Never a Girl Online?", "https://aniwave.to/watch/and-you-thought-there-is-never-a-girl-online.1n0v/ep-1", "Comedy, Ecchi, Romance, School", "", "", "", "", "", "x", "", "maybe", "3", "", "28-11-18", "", "02-08-23", "Dub", "", ""));
         */
        return animeData;
    }
}
