package stud.kea.dk.scrapbasketsultimateproject.repository;

import org.springframework.stereotype.Repository;
import stud.kea.dk.scrapbasketsultimateproject.model.AnimeData;

import java.util.ArrayList;
import java.util.List;

@Repository
public class AnimeRepository {
    public List<AnimeData> getAllAnimeData() {
        List<AnimeData> animeData = new ArrayList<>();
        animeData.add(new AnimeData(1, "Angel Beats!", "https://aniwave.to/watch/angel-beats.lzz/ep-1", "Action, Comedy, Drama, School, Supernatural", " ", " ", " ", "x", " ", "Yes", "2", "20-10-18", "02-08-23", "Dub", " ", " "));
        animeData.add(new AnimeData(2, "Re:Zero Starting Life in Another World", "https://aniwave.to/filter?keyword=Re%3AZero+Starting+Life+in+Another+World", "Drama, Fantasy, Psychological, Thriller", "", "", "", "", "x+++", "yes", "10+", "20-10-18", "22-04-23", "Dub", "", ""));
        animeData.add(new AnimeData(3, "No Game, No Life", "https://aniwave.to/filter?keyword=No+Game%2C+No+Life", "Adventure, Comedy, Fantasy, Game, Supernatural", "", "", "", "", "x+", "yes", "8", "09-10-18", "02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(4, "Sword Art Online", "https://aniwave.to/filter?keyword=Sword+Art+Online", "Action, Adventure, Fantasy, Game, Romance", "", "", "", "", "x++", "yes", "10+", "09-10-18", "02-08-23", "Dub", "Yes", "https://manganato.com/search/story/sword_art_online"));
        animeData.add(new AnimeData(5, "AntiMagic Academy 35th Test Platoon", "https://aniwave.to/watch/anti-magic-academy-the-35th-test-platoon.n3k/ep-1", "Action, Fantasy, Harem, Military, Romance, Supernatural", "", "", "x", "", "","no", "", "02-10-18", "02-08-23", "Sub", "", ""));
        animeData.add(new AnimeData(6, "Campione!", "https://aniwave.to/watch/campione.rkp/ep-1", "Comedy, Fantasy, Harem, Magic, Romance", "", "", "x", "", "","no","", "02-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(7, "Highschool DxD", "https://aniwave.to/filter?keyword=Highschool+DxD", "Comedy, Demons, Ecchi, Harem, Romance, School", "", "", "", "", "x+", "yes","2","27-09-18", "02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(8, "Freezing", "https://aniwave.to/filter?keyword=Freezing", "Action, Drama, Ecchi, Harem, Martial Arts, Romance, Sci-Fi, Seinen", "", "", "", "x", "", "yes","2", "01-10-18", "02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-sk953193"));
        animeData.add(new AnimeData(9, "Hajimate no Gal", "https://aniwave.to/watch/my-first-girlfriend-is-a-gal.wyrl/ep-1", "Comedy, Romance, School, Shounen", "", "x", "", "", "", "no", "","07-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(10, "Heaven's Lost Property", "https://aniwave.to/filter?keyword=Heaven%27s+Lost+Property", "Comedy, Ecchi, Harem, Sci-Fi, Shounen, Supernatural", "", "", "", "x", "","yes","2", "24-09-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-yc956437"));
        animeData.add(new AnimeData(11, "Highschool of the Dead", "https://aniwave.to/watch/high-school-of-the-dead.1n5q/ep-1", "Action, Horror, Supernatural", "", "", "", "", "x+", "no", "", "02-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-nu964455"));
        animeData.add(new AnimeData(12, "Rosario to Vampire", "https://aniwave.to/watch/rosario-vampire.jvpn/ep-1", "Comedy, Fantasy, Harem, Romance, School, Shounen, Vampire", "", "", "x", "", "", "no", "", "02-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(13, "Sekirei", "https://aniwave.to/watch/sekirei.lll3/ep-1", "Action, Comedy, Ecchi, Harem, Super Power", "", "", "x", "", "", "no", "","29-09-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(14, "So, I Can't Play H!", "https://aniwave.to/watch/so-i-cant-play-h.z1mw/ep-1", "Comedy,Romance, Supernatural", "x", "", "", "", "", "No", "","01-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(15, "The Devil is a Part-Timer!", "https://aniwave.to/filter?keyword=The+Devil+is+a+Part-Timer%21", "Comedy, Demons, Fantasy, Romance, Shounen, Shounen Ai", "", "", "", "", "x+", "yes","5","03-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-io951697"));
        animeData.add(new AnimeData(16, "The Testament of Sister New Devil", "https://aniwave.to/watch/the-testament-of-sister-new-devil.42rm/ep-1", "Action, Ecchi, Fantasy, Harem, Romance", "", "", "x", "", "", "no", "","29-09-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(17, "Ah! my Goddess", "https://aniwave.to/filter?keyword=Ah%21+my+Goddess", "Comedy, Magic, Romance, Seinen, Supernatural", "", "", "x", "", "", "no", "","08-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-mz955208"));
        animeData.add(new AnimeData(18, "Goblin Slayer", "https://aniwave.to/filter?keyword=Goblin+Slayer", "Action, Adventure, Fantasy, Magic", "", "", "", "", "x", "yes","5","08-10-18","02-08-23", "Sub", "yes", "https://chapmanganato.to/manga-us971827"));
        animeData.add(new AnimeData(19, "Accel World", "https://aniwave.to/filter?keyword=Accel+World", "Action, Romance, School, Sci-Fi, Isekai", "", "", "", "x", "","maybe", "", "15-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-ob952758"));
        animeData.add(new AnimeData(20, "Future Diary", "https://aniwave.to/watch/future-diary.ozj/ep-1", "Action, Horror, Mystery, Psychological, Shounen, Supernatural, Thriller, Suspense", "", "", "", "x", "", "maybe", "","18-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(21, "Btooom!", "https://aniwave.to/watch/btooom.z883/ep-1", "Action, Psychological, Sci-Fi, Seinen", "", "", "x", "", "","no", "", "17-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-jd954886"));
        animeData.add(new AnimeData(22, "Log Horizon", "https://aniwave.to/filter?keyword=Log+Horizon", "Action, Adventure, Fantasy, Isekai, Magic", "", "", "x", "", "","yes","4", "12-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(23, "Hack // Sign", "https://aniwave.to/watch/hacksign.wqqk/ep-1", "Adventure, Fantasy, Mystery, Sci-Fi, Super Power, Isekai, Magic", "", "x", "", "", "", "no","", "N/A","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(24, "Love Hina", "https://aniwave.to/filter?keyword=Love+Hina", "Comedy, Ecchi, Harem, Romance, Shounen, Slice of Life", "", "", "x", "", "","maybe","", "08-09-18","02-08-23", "Dub", "yes", "https://manganato.com/manga-cs956801"));
        animeData.add(new AnimeData(25, "Mahou Sensei Negima!", "https://aniwave.to/filter?keyword=Mahou+Sensei+Negima%21", "Comedy, Ecchi, Fantasy, Harem, Romance, School, Shounen, Super Power, Supernatural, Vampire, Magic", "", "", "", "x","", "maybe","", "08-09-18","02-08-23", "Dub", "yes", "https://chapmanganato.to//manga-av956604"));
        animeData.add(new AnimeData(26, "UQ Holder", "https://aniwave.to/watch/uq-holder.79qj/ep-1", "Action, Fantasy, School, Sci-Fi, Shounen, Vampire, Magic", "", "", "", "x", "","maybe","", "13-09-18","02-08-23", "Sub", "yes", "https://chapmanganato.to/manga-ro952049"));
        animeData.add(new AnimeData(27, "One punch man", "https://aniwave.to/filter?keyword=One+punch+man", "Action, Comedy, Parody, Sci-Fi, Seinen, Super Power, Supernatural, Demons", "", "", "", "x", "","maybe","", "N/A","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-wd951838"));
        animeData.add(new AnimeData(28, "Chobits", "https://aniwave.to/watch/chobits.29ql/ep-1", "Comedy, Drama, Ecchi, Romance, Sci-Fi, Seinen", "", "", "x", "", "","no", "", "07-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-tp955950"));
        animeData.add(new AnimeData(29, "Zombieland-Saga", "https://aniwave.to/filter?keyword=Zombieland-Saga", "Comedy, Music, Parody, Supernatural", "", "", "x", "", "","no","", "21-10-18","02-08-23", "Sub", "", ""));
        animeData.add(new AnimeData(30, "One Piece (Ongoing)", "https://aniwave.to/filter?keyword=One+Piece", "Action, Adventure, Comedy, Drama, Fantasy, Shounen, Super Power", "", "", "", "x", "", "maybe","", "N/A","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-aa951409"));
        animeData.add(new AnimeData(31, "Naruto", "https://aniwave.to/filter?keyword=Naruto", "Action, Adventure, Comedy, Drama, Fantasy, Martial Arts, School, Shounen, Super Power, Supernatural, Demons", "", "", "", "x", "","yes", "2","N/A","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-ng952689"));
        animeData.add(new AnimeData(32, "Boruto Next generation (Ongoing)", "https://aniwave.to/filter?keyword=Boruto+Next+generation", "Action, Adventure, Fantasy, Martial Arts, School, Shounen, Super Power", "", "", "x", "", "","no", "2","N/A","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-tl971246"));
        animeData.add(new AnimeData(33, "ReLIFE", "https://aniwave.to/watch/relife.yk0/ep-1", "Comedy, Drama, Romance, School, Seinen, Slice of Life", "", "", "", "", "x","yes", "2","20-10-18","02-08-23", "Dub", "yes", "https://chapmanganato.to/manga-me951739"));
        animeData.add(new AnimeData(34, "Grimgar: Ashes and Illusion", "https://aniwave.to/watch/grimgar-of-fantasy-and-ash.41k/ep-1", "Action, Adventure, Drama, Fantasy, Isekai, Magic", "", "", "", "", "x","yes", "6","21-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(35, "Interviews With Monster Girls", "https://aniwave.to/filter?keyword=Interviews+With+Monster+Girls", "Comedy, Fantasy, School, Seinen, Slice of Life, Supernatural, Vampire", "", "", "", "", "x+","yes","10+","22-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(36, "Overlord", "https://aniwave.to/filter?keyword=Overlord", "Action, Adventure, Fantasy, Vampire, Isekai, Demons, Magic", "", "", "", "", "x+","yes", "10+","19-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(37, "Miss Kobayashi's Dragon Maid", "https://aniwave.to/filter?keyword=Miss+Kobayashi%27s+Dragon+Maid", "Comedy, Fantasy, Seinen, Slice of Life, Isekai, Magic", "", "", "", "", "x+","yes", "5","23-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(38, "Monster Musume: Everyday Life with Monster Girls", "https://aniwave.to/filter?keyword=Monster+Musume%3A+Everyday+Life+with+Monster+Girls", "Comedy, Ecchi, Fantasy, Harem, Romance, Seinen, Demons", "", "", "", "x", "","maybe", "", "24-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(39, "Is It Wrong to Try to Pick Up Girls in a Dungeon?", "https://aniwave.to/filter?keyword=Is+It+Wrong+to+Try+to+Pick+Up+Girls+in+a+Dungeon%3F", "Action, Adventure, Comedy, Fantasy, Romance, Isekai, Magic", "", "", "", "", "x+++","yes", "10+","24-10-18","02-08-23", "Dub", "", ""));
        animeData.add(new AnimeData(40, "Sword Oratoria: Is it Wrong to Try to Pick Up Girls in a Dungeon?", "https://aniwave.to/watch/sword-oratoria-is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon-on-the-side.k8wr/ep-1", "Action, Adventure, Comedy, Fantasy, Magic", "", "", "", "x", "","maybe", "3", "27-10-18","02-08-23", "Dub", "", ""));
        return animeData;
    }
}
